package exceptions

import "errors"

var TransferDone = errors.New("传输完成！")
